# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Mohammad Mahdi Baghbani Pourvahid <mahdi-baghbani@azadehafzar.io>
#
# OpenCloudMesh Go - a runnable Open Cloud Mesh peer in Go, focused on a strict, WebDAV-centered subset of the protocol.

# Regenerate or verify the golangci inventory block in docs/lint-policy.md (.golangci.yml is SSOT).

const POLICY_DOC = 'docs/lint-policy.md'
const BEGIN_MARKER = '<!-- golangci-disable-inventory:begin -->'
const END_MARKER = '<!-- golangci-disable-inventory:end -->'
const GENERATED_COMMENT = '<!-- Generated by `nu .github/scripts/lint-policy-drift-check.nu --write`; .golangci.yml is the SSOT. Do not edit by hand. -->'

def build-policy-record [cfg: record] {
  let linters = ($cfg | get --optional linters | default {})
  let settings = ($linters | get --optional settings | default {})
  let exclusions = ($linters | get --optional exclusions | default {})
  let formatters = ($cfg | get --optional formatters | default {})
  let formatter_settings = ($formatters | get --optional settings | default {})
  let goimports = ($formatter_settings | get --optional goimports | default {})
  let issues = ($cfg | get --optional issues | default {})
  let severity = ($cfg | get --optional severity | default {})
  let run = ($cfg | get --optional run | default {})

  let cyclop = ($settings | get --optional cyclop | default {})
  let errcheck = ($settings | get --optional errcheck | default {})
  let govet = ($settings | get --optional govet | default {})
  let modernize = ($settings | get --optional modernize | default {})
  let staticcheck = ($settings | get --optional staticcheck | default {})
  let revive = ($settings | get --optional revive | default {})
  let errchkjson = ($settings | get --optional errchkjson | default {})
  let nolintlint = ($settings | get --optional nolintlint | default {})
  let tagliatelle = ($settings | get --optional tagliatelle | default {})
  let tagliatelle_case = ($tagliatelle | get --optional case | default {})
  let tagliatelle_rules = ($tagliatelle_case | get --optional rules | default {})
  let gosec = ($settings | get --optional gosec | default {})

  {
    run: {
      modules-download-mode: ($run | get --optional modules-download-mode | default null)
    }
    linters: {
      default: ($linters | get --optional default | default null)
      disable: ($linters | get --optional disable | default null)
      settings: {
        cyclop: {
          max-complexity: ($cyclop | get --optional max-complexity | default null)
          package-average: ($cyclop | get --optional package-average | default null)
        }
        errcheck: {
          check-type-assertions: ($errcheck | get --optional check-type-assertions | default null)
          check-blank: ($errcheck | get --optional check-blank | default null)
          disable-default-exclusions: ($errcheck | get --optional disable-default-exclusions | default null)
          verbose: ($errcheck | get --optional verbose | default null)
          exclude-functions: ($errcheck | get --optional exclude-functions | default null)
        }
        govet: {
          enable-all: ($govet | get --optional enable-all | default null)
          disable: ($govet | get --optional disable | default null)
        }
        modernize: {
          disable: ($modernize | get --optional disable | default null)
        }
        staticcheck: {
          checks: ($staticcheck | get --optional checks | default null)
        }
        revive: {
          enable-all-rules: ($revive | get --optional enable-all-rules | default null)
          rules: ($revive | get --optional rules | default null)
        }
        errchkjson: {
          check-error-free-encoding: ($errchkjson | get --optional check-error-free-encoding | default null)
          report-no-exported: ($errchkjson | get --optional report-no-exported | default null)
        }
        nolintlint: {
          require-explanation: ($nolintlint | get --optional require-explanation | default null)
          require-specific: ($nolintlint | get --optional require-specific | default null)
        }
        tagliatelle: {
          case: {
            rules: {
              json: ($tagliatelle_rules | get --optional json | default null)
            }
          }
        }
        gosec: {
          excludes: ($gosec | get --optional excludes | default null)
        }
      }
      exclusions: {
        generated: ($exclusions | get --optional generated | default null)
        presets: ($exclusions | get --optional presets | default null)
        rules: ($exclusions | get --optional rules | default null)
      }
    }
    formatters: {
      settings: {
        goimports: {
          local-prefixes: ($goimports | get --optional local-prefixes | default null)
        }
      }
    }
    issues: {
      max-issues-per-linter: ($issues | get --optional max-issues-per-linter | default null)
      max-same-issues: ($issues | get --optional max-same-issues | default null)
      uniq-by-line: ($issues | get --optional uniq-by-line | default null)
    }
    severity: {
      default: ($severity | get --optional default | default null)
      rules: ($severity | get --optional rules | default null)
    }
  }
}

def quote-yaml-trailing-colons [yaml: string] {
  $yaml | lines | each {|l|
    if ($l =~ ':\s+\S.*:\s*$') {
      let m = ($l | parse -r '^(?<prefix>.*:\s+)(?<value>.*:\s*)$' | first)
      let escaped = ($m.value | str replace -a '\' '\\' | str replace -a '"' '\"')
      $"($m.prefix)\"($escaped)\""
    } else {
      $l
    }
  } | str join (char nl)
}

def build-doc-block [cfg: record] {
  let yaml = (quote-yaml-trailing-colons (build-policy-record $cfg | to yaml))
  ([
    $GENERATED_COMMENT
    ''
    '```yaml'
    $yaml
    '```'
    ''
    ''
  ] | str join (char nl))
}

def trim-block-edges [block: string] {
  $block | str trim --char (char nl)
}

def split-inventory-block [text: string] {
  let begin_pos = ($text | str index-of $BEGIN_MARKER)
  let end_pos = ($text | str index-of $END_MARKER)
  if $begin_pos < 0 or $end_pos < 0 {
    print --stderr $"($POLICY_DOC): missing inventory markers; expected ($BEGIN_MARKER) and ($END_MARKER)"
    exit 1
  }
  if $end_pos <= $begin_pos {
    print --stderr $"($POLICY_DOC): end marker appears before begin marker"
    exit 1
  }

  let after_begin = ($begin_pos + ($BEGIN_MARKER | str length))
  {
    before: ($text | str substring 0..$after_begin)
    current: ($text | str substring $after_begin..($end_pos - 1))
    after: ($text | str substring $end_pos..)
  }
}

def main [--write] {
  let cfg = (open .golangci.yml)
  let expected = (build-doc-block $cfg)
  let doc_text = (open --raw $POLICY_DOC)
  let parts = (split-inventory-block $doc_text)

  if $write {
    let new_text = ([$parts.before $expected $parts.after] | str join '')
    $new_text | save -f $POLICY_DOC
    print 'lint-policy-drift: written'
    return
  }

  let current = (trim-block-edges $parts.current)
  let want = (trim-block-edges $expected)
  if $current != $want {
    print --stderr 'lint-policy-drift: docs/lint-policy.md inventory block is stale'
    print --stderr '--- current'
    print --stderr $current
    print --stderr '+++ expected'
    print --stderr $want
    exit 1
  }

  print 'lint-policy-drift: OK'
}
