package spec_test

import (
	"fmt"
	"go/ast"
	"go/build/constraint"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/MahdiBaghbani/opencloudmesh-go/internal/testsupport/modroot"
)

// wireLiteralSet contains all OCM wire values owned by the spec package.
// The scanner flags any raw production string literal in this set that is not
// in the explicit allowlist.
var wireLiteralSet = []string{
	// Capabilities
	"http-sig",
	"exchange-token",
	"invites",
	"invite-wayf",

	// Criteria
	"must-use-http-sig",

	// Requirements
	"must-exchange-token",
	"must-use-mfa",

	// Protocol role names
	"webdav",
	"webdav-receive",

	// Signature label
	"ocm",
}

// wireLiteralAllowlist enumerates file/line exceptions where a raw value from
// wireLiteralSet appears in production code but is not an OCM wire literal
// owned by spec (e.g., service identifiers, route/build keys, or constants in
// packages owned by prior tasks). New exceptions must be added explicitly;
// wildcards are not allowed.
var wireLiteralAllowlist = map[string]map[int]struct{}{
	"internal/components/ocm/access/remote.go": {
		32: {},
	},
	"internal/components/ocm/outbound/kinds.go": {
		11: {},
	},
	"internal/frameworks/service/descriptors.go": {
		9:  {},
		13: {},
		34: {},
		36: {},
		58: {},
		60: {},
	},
	"internal/frameworks/service/route_aggregate.go": {
		113: {},
		121: {},
	},
	"internal/frameworks/service/route_opts.go": {
		47: {},
	},
	"internal/frameworks/service/route_specs.go": {
		32: {},
		58: {},
	},
	"internal/platform/config/loader.go": {
		668: {},
	},
	"internal/platform/crypto/sigparams/label.go": {
		4: {},
	},
	"internal/services/ocm/mount.go": {
		46: {},
	},
	"internal/services/ocm/ocm.go": {
		51:  {},
		133: {},
	},
	"internal/services/ocm/routes.go": {
		29: {},
		41: {},
		53: {},
	},
	"internal/services/ui/routes.go": {
		59: {},
	},
	"internal/services/webdav/routes.go": {
		19: {},
	},
	"internal/services/webdav/webdav.go": {
		41: {},
		47: {},
		61: {},
	},
}

func TestWireConstantsOwnedBySpec(t *testing.T) {
	root := modroot.ModuleRoot(t)

	violations, err := scanRawWireLiterals(root, wireLiteralSetAsMap(), wireLiteralAllowlist)
	if err != nil {
		t.Fatalf("scan failed: %v", err)
	}
	if len(violations) > 0 {
		t.Fatalf("Raw wire literals outside allowlist:\n%s", strings.Join(violations, "\n"))
	}
}

func TestWireConstantsScannerDetectsViolation(t *testing.T) {
	t.Parallel()

	tmp := t.TempDir()
	src := `package bad

func init() { _ = "must-exchange-token" }
`
	path := filepath.Join(tmp, "pkg", "bad.go")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("mkdir temp fixture: %v", err)
	}
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatalf("write temp fixture: %v", err)
	}

	literals := wireLiteralSetAsMap()
	violations, err := scanRawWireLiterals(tmp, literals, wireLiteralAllowlist)
	if err != nil {
		t.Fatalf("scan failed: %v", err)
	}

	want := `pkg/bad.go:3: raw wire literal "must-exchange-token"`
	if !slices.Contains(violations, want) {
		t.Fatalf("expected violation %q, got:\n%s", want, strings.Join(violations, "\n"))
	}
}

func TestWireConstantsScannerSkipsGeneratedFiles(t *testing.T) {
	t.Parallel()

	tmp := t.TempDir()
	literals := wireLiteralSetAsMap()

	cases := []struct {
		dir     string
		src     string
		skipped bool
	}{
		{
			dir:     "header_blank",
			src:     "// Code generated by mockgen. DO NOT EDIT.\n\npackage headerblank\n\nfunc init() { _ = \"must-exchange-token\" }\n",
			skipped: true,
		},
		{
			dir:     "positive_tag",
			src:     "//go:build generated\n\npackage positivetag\n\nfunc init() { _ = \"must-exchange-token\" }\n",
			skipped: true,
		},
		{
			dir:     "negative_tag",
			src:     "//go:build !generated\n\npackage negativetag\n\nfunc init() { _ = \"must-exchange-token\" }\n",
			skipped: false,
		},
	}

	for _, tc := range cases {
		dir := filepath.Join(tmp, tc.dir)
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatalf("mkdir temp fixture %s: %v", tc.dir, err)
		}
		path := filepath.Join(dir, "pkg.go")
		if err := os.WriteFile(path, []byte(tc.src), 0644); err != nil {
			t.Fatalf("write temp fixture %s: %v", tc.dir, err)
		}
	}

	violations, err := scanRawWireLiterals(tmp, literals, wireLiteralAllowlist)
	if err != nil {
		t.Fatalf("scan failed: %v", err)
	}

	for _, tc := range cases {
		rel := tc.dir + "/pkg.go"
		count := 0
		for _, v := range violations {
			if strings.HasPrefix(v, rel+":") {
				count++
			}
		}
		if tc.skipped {
			if count != 0 {
				t.Errorf("expected %s to be skipped, got violations:\n%s", rel, strings.Join(violations, "\n"))
			}
		} else {
			if count != 1 {
				t.Errorf("expected %s to be reported as a violation, got %d matching violations:\n%s", rel, count, strings.Join(violations, "\n"))
			}
		}
	}
}

func wireLiteralSetAsMap() map[string]struct{} {
	literals := make(map[string]struct{}, len(wireLiteralSet))
	for _, lit := range wireLiteralSet {
		literals[lit] = struct{}{}
	}
	return literals
}

func scanRawWireLiterals(root string, literals map[string]struct{}, allowlist map[string]map[int]struct{}) ([]string, error) {
	var violations []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)

		if !strings.HasSuffix(rel, ".go") || strings.HasSuffix(rel, "_test.go") {
			return nil
		}
		if isSpecOwnedProductionFile(rel) {
			return nil
		}

		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", rel, err)
		}

		if isGeneratedFile(f) {
			return nil
		}

		allowed := allowlist[rel]
		ast.Inspect(f, func(n ast.Node) bool {
			if field, ok := n.(*ast.Field); ok && field.Tag != nil {
				// Struct tags are raw string syntax but not wire values;
				// skip the tag literal so JSON/TOML/mapstructure keys do not
				// produce false positives.
				return false
			}
			if imp, ok := n.(*ast.ImportSpec); ok {
				// Import paths are string literals but never OCM wire values.
				_ = imp
				return false
			}

			lit, ok := n.(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}

			val, err := strconv.Unquote(lit.Value)
			if err != nil {
				// Raw string literals are also quoted by the parser; if
				// Unquote fails, trim the surrounding backticks.
				val = strings.Trim(lit.Value, "`")
			}
			if _, match := literals[val]; !match {
				return true
			}

			pos := fset.Position(lit.Pos())
			if _, ok := allowed[pos.Line]; ok {
				return true
			}

			violations = append(violations, fmt.Sprintf("%s:%d: raw wire literal %q", rel, pos.Line, val))
			return true
		})
		return nil
	})
	if err != nil {
		return nil, err
	}
	return violations, nil
}

func isSpecOwnedProductionFile(rel string) bool {
	return strings.HasPrefix(rel, "internal/components/ocm/spec/") && strings.HasSuffix(rel, ".go")
}

func isGeneratedFile(f *ast.File) bool {
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "Code generated") {
				return true
			}
			if constraint.IsGoBuild(c.Text) {
				expr, err := constraint.Parse(c.Text)
				if err == nil && hasPositiveGeneratedTag(expr) {
					return true
				}
			}
		}
	}
	return false
}

func hasPositiveGeneratedTag(expr constraint.Expr) bool {
	switch e := expr.(type) {
	case *constraint.TagExpr:
		return e.Tag == "generated"
	case *constraint.NotExpr:
		return false
	case *constraint.AndExpr:
		return hasPositiveGeneratedTag(e.X) || hasPositiveGeneratedTag(e.Y)
	case *constraint.OrExpr:
		return hasPositiveGeneratedTag(e.X) || hasPositiveGeneratedTag(e.Y)
	}
	return false
}
