# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Mohammad Mahdi Baghbani Pourvahid <mahdi-baghbani@azadehafzar.io>
#
# Run OpenSSF Scorecard on master pushes and weekly.

name: Scorecard

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3
        with:
          sarif_file: results.sarif
          category: scorecard
